# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

subir-a-dev:
  # La imagen cuenta con openssh, lftp y mkdocs
  image: industriaspugliesesa/mkdocs-lftp:latest
  
  stage: deploy
  script:
    - mkdir ~/.ssh
    - ssh-keyscan -H $DEV_SFTP_HOST >> ~/.ssh/known_hosts
    - echo -e "\E[1;34mGenerando carpetas\E[0m"
    - CARPETA_ORIGEN="proyector"
    - CARPETA_DESTINO="proyector"
    - echo "Se subira el contenido de la carpeta origen «$CARPETA_ORIGEN» en la carpeta destino «$CARPETA_DESTINO»."  
    - eval $(echo "lftp -u '$DEV_SFTP_USER,$DEV_SFTP_PASS' sftp://$DEV_SFTP_HOST -e \" cd $CARPETA_DESTINO || mkdir -p $CARPETA_DESTINO ;quit\"")
    - eval $(echo "lftp -u '$DEV_SFTP_USER,$DEV_SFTP_PASS' sftp://$DEV_SFTP_HOST -e \" mirror -Rnev --ignore-time --parallel=10 ./$CARPETA_ORIGEN $CARPETA_DESTINO; quit\"")
    - echo "Todos los archivos subidos."
  only:
    - development
  tags:
    - shared

subir-a-doc:
  # Se suben los cambios al ambiente de documentación.
  # La imagen cuenta con openssh, lftp y mkdocs
  image: industriaspugliesesa/mkdocs-lftp:latest
  
  stage: deploy
  script:
    - mkdir ~/.ssh
    - ssh-keyscan -H $DOC_SFTP_HOST >> ~/.ssh/known_hosts
    - echo -e "\E[1;34mGenerando carpetas\E[0m"
    - CARPETA_ORIGEN="proyector"
    - CARPETA_DESTINO="proyector"
    - echo "Se subira el contenido de la carpeta origen «$CARPETA_ORIGEN» en la carpeta destino «$CARPETA_DESTINO»."
    - eval $(echo "lftp -u '$DOC_SFTP_USER,$DOC_SFTP_PASS' sftp://$DOC_SFTP_HOST -e \" cd $CARPETA_DESTINO || mkdir -p $CARPETA_DESTINO ;quit\"")
    - eval $(echo "lftp -u '$DOC_SFTP_USER,$DOC_SFTP_PASS' sftp://$DOC_SFTP_HOST -e \" mirror -Rnev --ignore-time --parallel=10 ./$CARPETA_ORIGEN $CARPETA_DESTINO; quit\"")
    - echo "Todos los archivos subidos."
  only:
    - master
  tags:
    - shared
