install: gem install rails
before_install: gem install bundler --pre
language: ruby
rvm:
  - 2.5
  - 2.6
  - jruby
  - truffleruby 
deploy:
  provider: heroku
  api_key: bQBJhR40Lif50z5VCJtJRJhPhXtiX0cWnvChTVE0japrB48s+V39Tp2mfFNjF/BHy5Onfi5c12XOj7GM2M0hIxWhCRUlKiXJRHHMSJMCzLOWwU7RVgckJSLaJhi6WHaFk6Dr7pfLCz23yb64rpzOL45cT+Q0RJVwriC7ONmsuKtfEjkQ+6kMBzWcDvduDYp3T3q3MSdLeOSnZljvVUgluVrN2kgRqXBCrv0zpWV/+s1bY0aWFvZosCRpC9ijIsVmID/mWrOcZ+o8C5nGYcfif+Lsq7flyCP7PN2rHUCbdsMhSN3L6K1xkVLO/vaiD/XqLHLts2FGsJeA4vYLtMfUARddSa11C3GSQ0qQqMKpv3FKE3GsshOn5l1w+Yzf4n24oapU0Pz32Vb7HXDSfrpX9Zvi93Iuxm0jS/YGI17dlJdem29CEncHUDObZNc0eVdZtPQZQJGCQpnMkOT3D8HMJ/RSNs8KF0he2L5uC/nJcK0qioFbW/81TllyrYLi1LxxLFkZdYrLxpqmOMYqstrIcKIJ5ADbk6mdS9FyZeOcLUeNet9dtzepalpldEuL+fsU4vBxhfkCY/+VaPVFQjgTdZxJ9FiTcRMgkK6KLKQPJOAL/GY6eVX2uLu1PYrK5C9RBVw1LZuRMncdcrTznZFU+1jhjZG91QlVcx8TrEAClwg=
  app: omarhectorsosa-proyector
